services:
  - type: web
    name: notes-api
    rootDir: Backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn notes_api.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notes-db
          property: connectionString
      - key: SECRET_KEY
        value: supersecret
      - key: PYTHON_VERSION
        value: "3.11"

  - type: web
    name: notes-frontend
    rootDir: Frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: "18"

