services:
  - type: web
    name: notes-api
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notes-db
          property: connectionString
      - key: SECRET_KEY
        value: supersecret
      - key: PYTHON_VERSION
        value: "3.11"

databases:
  - name: notes-db
    databaseName: notes
    user: notes_user
